import Head from "next/head";
import { Inter } from "@next/font/google";
import style from "../styles/Home.module.css";
import commerce from "../lib/commerce";
import { useState } from "react";
import Link from "next/link";
import Product from "../components/Product/Product";

const inter = Inter({ subsets: ["latin"] });

export async function getStaticProps(context) {
  const { data: products } = await commerce.products.list();
  const { data: categories } = await commerce.categories.list();
  return {
    props: { products, categories },
    revalidate: 30,
  };
}

export default function Home({ products, categories, addToCart, emptyCart }) {
  const [searchTerm, setSearchTerm] = useState("");

  return (
    <>
      <Head>
        <title>E store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <main className={`${style.main} `}>
        <input
          value={searchTerm}
          onChange={(e) => {
            setSearchTerm(e.target.value);
          }}
          className="text-center mb-10 border-2 border-gray-500"
          role="searchbox"
          type="text"
          title="Search"
          placeholder="Search products..."
        />

        {searchTerm.length > 0 ? (
          <>
            <h2 id="search-results-heading">Search results</h2>
            <ul aria-labelledby="search-results-heading">
              {products
                .filter((product) =>
                  product.name.toLowerCase().includes(searchTerm.toLowerCase())
                )
                .map((product) => {
                  return (
                    <li key={product.id}>
                      <Product
                        product={product}
                        addToCart={() => {
                          addToCart(product.id);
                        }}
                      />
                    </li>
                  );
                })}
            </ul>
          </>
        ) : (
          <>
            <ul aria-label="Categories" className="mb-10">
              {categories.map((category) => {
                return (
                  <li key={category.id} aria-label="category">
                    <h2
                      className="text-blue-500 font-bold text-2xl"
                      id={`category-${category.name}`}
                    >
                      {category.name}
                    </h2>
                    <ul aria-labelledby={`category-${category.name}`}>
                      {products
                        .filter((product) =>
                          product.categories.find((c) => c.id === category.id)
                        )
                        .map((product) => {
                          return (
                            <li key={product.id}>
                              <Product
                                product={product}
                                addToCart={() => {
                                  addToCart(product.id);
                                }}
                              />
                            </li>
                          );
                        })}
                    </ul>
                  </li>
                );
              })}
            </ul>

            <h2
              id="all-products-heading"
              className="text-center text-red-500 font-extrabold text-4xl cursor-pointer"
            >
              All Products
            </h2>
            <ul aria-labelledby="all-products-heading">
              {products.map((product) => {
                return (
                  <li
                    key={product.id}
                    className="cursor-pointer hover:text-blue-700"
                  >
                    {/* {product.name} */}
                    <Product
                      product={product}
                      addToCart={() => {
                        addToCart(product.id);
                      }}
                    />
                  </li>
                );
              })}
            </ul>

            <button
              className="bg-gray-100 rounded-md px-8 py-2"
              onClick={() => {
                emptyCart();
              }}
            >
              {" "}
              Delete{" "}
            </button>

            {/* <div onClick={() => addToCart('prod_p6dP5gMnp8wn7k')}> add to cart</div>  */}
          </>
        )}
      </main>
    </>
  );
}
